import LayoutProvider from "@/components/LayoutProvider";
import "@/styles/globals.css";
import { Nunito } from "next/font/google";
import { Toaster } from "react-hot-toast";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
   title: "LINKIM",
   description: "Generated by create next app",
   icons: {
      icon: "/favicon.png",
   },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={`${nunito.className} h-full`}>
            <LayoutProvider>
               <main className="flex-1">
                  <div className="container px-5 h-full">{children}</div>
               </main>
               <Toaster position="top-right" reverseOrder={false} />
            </LayoutProvider>
         </body>
      </html>
   );
}
